### PR TITLE
Update dashboard schema to include date field

### PR DESCRIPTION
**Pull request by guid3d**
- Update Dashboard API to latest
- Fix missing <Content> on Dashboard from merge development
- Connect Success Rate Graph to Real API

### CODE REVIEW

**Comment by GLDuval** [comment]
Not sure if this current chart implementation is representative for our dashboard. I was maybe thinking of something more like we display the average success rate of each day? Because with this implementation it doesn't really show the overtime aspect that we ideally want to show.

**Comment by guid3d** [comment]
I agree on what you say, the x axis should be the date somehow.
Moreover, the graph now is like a rectangle, since all is around 80% and it looks funny.

**Comment by guid3d** [comment]
But the data that is return from the backend also need to be changed as well then?, bc what return now is
 ```
{
            "id": "6571d076c41d1389733d0572",
            "successRate": 0.8329350427350427,
            "date": 1701957750208
        }
```
which is specific for each simulation right?

**Review by GLDuval — DISMISSED** [review]
We can make this change after mid term review no rush

**Review by GLDuval — APPROVED** [review]

**Pull request merged**
